//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESoftApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coef
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coef()
        {
            this.Managers = new HashSet<Manager>();
        }
    
        public int Id { get; set; }
        public decimal Analysis { get; set; }
        public decimal Deployment { get; set; }
        public decimal Support { get; set; }
        public decimal Time { get; set; }
        public decimal Difficulty { get; set; }
        public decimal Transfer { get; set; }
        public int GradeCoefId { get; set; }
    
        public virtual GradeCoef GradeCoef { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manager> Managers { get; set; }
    }
}
