//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESoftApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeCoef
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GradeCoef()
        {
            this.Coefs = new HashSet<Coef>();
        }
    
        public int Id { get; set; }
        public decimal Junior { get; set; }
        public decimal Middle { get; set; }
        public decimal Senior { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coef> Coefs { get; set; }
    }
}
